### ISSUE TITLE
WYSIWYG overrides customized attributes

### ISSUE THREAD

**Issue by johnpennypacker** [uriweb/uri-component-library#144]
## Issue Type

[x] Bug  
[] New Feature  
[] Enhancement  
    
## Description

If you add a class attribute to a component, then later edit the component with the WYSIWYG editor, the WYSIWYG editor removed the class attribute.  And presumably any other attribute it doesn't expect.

In the same vein, if you have a card with attribute button="" the WYSIWYG converts it to button="Explore"

**Comment by bjcfuller** [comment]
Was this fixed in f25d95c21f906f21a09d9a79066affc483b6b564?

**Comment by johnpennypacker** [comment]
Yep.  Oops.

**Comment by bjcfuller** [comment]
:solid:
