### ISSUE TITLE
get_plugin_data() function errors on non-multisite WP instances

### ISSUE THREAD

**Issue by bjcfuller** [uriweb/uri-component-library#186]
## Description

The [`get_plugin_data()`](https://developer.wordpress.org/reference/functions/get_plugin_data/) function errors on non-multisite WP instances:

```
Uncaught Error: Call to undefined function get_plugin_data() in /Library/WebServer/Documents/wordpress/wp-content/plugins/uri-component-library/uri-component-library.php:38
```

This might be because plugins are loaded at a different point in time on non-multisite instances vs. multisite instances, and the function is not yet available.  If this is the case, calling the function through a hook might be better.

**Comment by johnpennypacker** [comment]
Fixed in
558ee82e16e37294db8fafad2c2b85ea69b877ab
