### ISSUE TITLE
Space below h1s in come components

### ISSUE THREAD

**Issue by scouch87** [uriweb/uri-component-library#35]
This is a small picky thing, and I know you're still messing with font sizes and headers, but on some components the h1s are a little tight with the text below (for example: boxout - https://www.uri.edu/harrington-draft/learning-spaces/the-hub/). On panels it seems fine unless there's a list underneath, for example: https://www.uri.edu/harrington-draft/learning-spaces/the-hub/labs-and-study-spaces/.

**Comment by bjcfuller** [comment]
Ah, yeah.  Thanks for the issue.  I think this will be resolved in the next release now that most of the local font styles have been wiped out, so all those headers will adopt theme styles.  But I will double check.

**Comment by bjcfuller** [comment]
This issue was fixed in 52a23b648363f323cff2dc5915957916c5fd9d21
