### ISSUE TITLE
Goldilocks hero?

### ISSUE THREAD

**Issue by johnpennypacker** [uriweb/uri-component-library#39]
superhero is the height of the browser window.  On a site where there are 300px of stuff above the hero (nav, branding, etc), that's too big, and the bottom 300px of the hero is outside of the window's display area.

fullwidth hero spans the full with, but we lose some height.

I propose a goldilocks superhero that magically knows when it's too high to too short. I think we need some sort of test.  For example, we might use the fold. If the hero is below the fold, then the hero's height is browser height minus a little bit.  If above, then we'll need a better test to figure out intent.  

I think the gist of it is that when we lead with a superhero, we probably want to make sure that the bottom of the hero is either aligned with the bottom of the window, or leaves a little space.

**Comment by bjcfuller** [comment]
Work is being done on the [`feature-superheros`](https://github.com/uriweb/uri-component-library/tree/feature-superheros) branch.
