### ISSUE TITLE
No line breaks on boxouts

### ISSUE THREAD

**Issue by scouch87** [uriweb/uri-component-library#44]
## Issue Type

[X] Bug  
[] New Feature  
[] Enhancement  
    
## Description

Line breaks don't work in boxouts (just noticed it in v0.3.0 on quack). I tried manually adding BR tags but that still didn't work.

Example: 

https://www.uri.edu/harrington-draft/learning-spaces/the-hub/
vs.
http://quack.uri.edu/harrington/learning-spaces/the-hub/

**Comment by bjcfuller** [comment]
`<br>` and empty `<p>` tags are not displayed in components to help with WP spacing issues.

see [`main.scss#L3-L6`](https://github.com/uriweb/uri-component-library/blob/a5ae74d53446515179cb0aa694f41fa9e467cd59/src/sass/main.scss#L3-L6):
```
*[class^="cl-"] br:empty,
*[class^="cl-"] p:empty {
    display: none;
}
```
I need to figure out a better workaround... I realize this isn't a great solution.  It might warrant a hotfix.
