### ISSUE TITLE
HTML inside of tabs breaks

### ISSUE THREAD

**Issue by johnpennypacker** [uriweb/uri-component-library#61]
## Issue Type

[x] Bug  
[] New Feature  
[] Enhancement  
    
## Description

[Description of the issue]

## Steps to Reproduce

1. place html inside a [cl-tab] shortcode.

**Comment by bjcfuller** [comment]
`[cl-tab]` is a self-closing shortcode and uses a `body` attribute for content.  It's not the HTML that's breaking it, it's just not looking for or using any `content`.
