### ISSUE TITLE
Multiple instances of cl-tabs

### ISSUE THREAD

**Issue by johnpennypacker** [uriweb/uri-component-library#95]
## Issue Type

[x] Bug  
[] New Feature  
[] Enhancement  
    
## Description

Multiple of instances of tabs on a single page misbehave.

## Steps to Reproduce

1. Create more than one instance of [cl-tabs] on a page
2. Select any tab that isn't the first one

**Expected behavior:** [What you expect to happen]

selected tab's content is displayed

**Actual behavior:** [What actually happens]

current tab's content remain's displayed; selected tab is highlighted, js console says, "TypeError: undefined is not an object (evaluating 's[n].hidden=!1')"

**Reproduces how often:** [What percentage of the time does it reproduce?]

https://www.youtube.com/watch?v=pjvQFtlNQ-M  (where 60 = 100)

**Additional information:** [Add any additional information useful in reproducing the problem]

## Environment

**Version:** X.x.x

**OS:** [please list]

**Browsers:** [please list]

**Comment by bjcfuller** [comment]
This was fixed in bd48e33d8ca78a1ce8685559d6332f5b793148ea but it didn't make it into [v2.3.4](https://github.com/uriweb/uri-component-library/releases/tag/2.3.4).  I should have fixed it on a branch 😞
